id: A0389F000
title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:14:21.421375
  last_modified_at: 2022-03-01 00:14:21.421384
